//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Food_Delivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Master()
        {
            this.Order_Master = new HashSet<Order_Master>();
        }
    
        public int CustomerID { get; set; }


        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please Enter name")]
        [RegularExpression(@"^[A-Za-z]*$|^[a-zA-Z]+\s[A-Za-z]*$|^[a-zA-Z]+\.[a-zA-Z]*$", ErrorMessage = "Please Enater Valid Name")]
        public string CustomerName { get; set; }


        [Display(Name = "Mo.Number")]
        [Required(ErrorMessage = "Please Enter Mobile Number")]
        [RegularExpression(@"^(?:(?:\+|0{0,2})91(\s*[\-]\s*|\s)?|[0]?)?[6789]\d{9}$", ErrorMessage = "Please Enater Valid Mobile Number")]
        public string MobileNumber { get; set; }


        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please Enter Email")]
        [RegularExpression(@"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$", ErrorMessage = "Please Enater Valid Email")]
        public string Email { get; set; }



        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please Enter Password")]
        [RegularExpression(@"^((?=\S*[a-z])(?=\S*[A-Z])(?=\S*\d)(?=\S*[^\w\s])\S{6,20})$", ErrorMessage = "Password Should be 6 characters long , 1 uppercase , 1 lowercase char , 1 number , 1 Special Char.")]
        [DataType(DataType.Password)]
        public string CustomerPassword { get; set; }


        [Required(ErrorMessage = "Please Enter City")]
        public string City { get; set; }


        [Required(ErrorMessage = "Please Enter House Number")]
        public string HouseNumber { get; set; }


        [Required(ErrorMessage = "Please Enter Street")]
        public string Street { get; set; }


        [Required(ErrorMessage = "Please Enter PostalCode")]
        [RegularExpression(@"^[0-9]{6}$", ErrorMessage = "Please Postal Code 6 Digit Only")]
        public Nullable<int> PostalCode { get; set; }

        public Nullable<bool> ISActive { get; set; }




        [Display(Name = "New Password")]
        [RegularExpression(@"^((?=\S*[a-z])(?=\S*[A-Z])(?=\S*\d)(?=\S*[^\w\s])\S{6,20})$", ErrorMessage = "Password Should be 6 characters long , 1 uppercase , 1 lowercase char , 1 number , 1 Special Char.")]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [Display(Name = "Confirm Password")]
        [Compare("NewPassword", ErrorMessage = "Password and Confirmation Password Not Matched")]
        [DataType(DataType.Password)]
        public string ConfirmPassowrd { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Master> Order_Master { get; set; }
    }
}
