//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Food_Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Master()
        {
            this.Order_Details_Master = new HashSet<Order_Details_Master>();
            this.Payment_Master = new HashSet<Payment_Master>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<DateTime> OrderDate { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<bool> CoockStatus { get; set; }
        public Nullable<bool> DeliveryStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details_Master> Order_Details_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Master> Payment_Master { get; set; }
        public virtual Customer_Master Customer_Master { get; set; }
    }
}
