//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Food_Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Master
    {
        public int Payment_ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual Order_Master Order_Master { get; set; }
    }
}
